spring.application.name=rag-agent

# Connect to your local Ollama instance
spring.ai.ollama.base-url=http://localhost:11434

# CHANGE: Match the name from your 'ollama list'
spring.ai.ollama.chat.options.model=llama3.1

# ADD: This is required for your Neo4j vector store to work
spring.ai.ollama.embedding.options.model=mxbai-embed-large
# spring.ai.ollama.model=llama3

# Connect to your Neo4j Database
spring.neo4j.uri=bolt://localhost:7687
spring.neo4j.authentication.username=neo4j
spring.neo4j.authentication.password=Password123

# This tells Spring AI to use Neo4j as the vector store
spring.ai.vectorstore.neo4j.initialize-schema=true

# Force non-streaming to avoid Aggregation Errors
spring.ai.ollama.chat.options.stream-usage=false

spring.ai.ollama.chat.options.stream=false

logging.level.org.springframework.ai=DEBUG
logging.level.org.springframework.web.reactive.function.client=DEBUG
